config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }

  resource :customers, only: [:show, :edit, :update]
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw'

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
    }


  root to: 'homes#top'
  get 'home/about' => 'homes#about'


  resources :items, only: [:index, :show]

  post '/orders/confirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:new, :create, :index, :show]



  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]


  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]

    root to: 'homes#top'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end

  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  enum status: {
  入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4
  }

  enum payment_option: {クレジットカード: 0, 銀行振込: 1}

  attr_accessor :address_a, :order
  validates :total_payment, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

    before_action :authenticate_admin!

  def show
     @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @order.update(order_params)
    if @order.status == "入金確認"
      @order_items.update_all(status: 1)
    end
    redirect_to admin_root_path
  end


  private

    # def order_item_params
    #   params.permit(:status).merge(status: 1)
    # end

    def order_params
      params.require(:order).permit(:status, order_item_attributes:[:id, :status])
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include ApplicationHelper


  before_action :authenticate_customer!

  def new
    @order = Order.new
    @customer = current_customer
    @all = Item.all
    @address = @customer.addresses
    # Address.where(customrer_id: @customer.id)
    @orders = Order.all
  end

  def confirm
    @cart_items = current_customer.cart_items
    @total = 0
    obj = address_params
    obj[:total_payment] = obj[:total_payment].to_i
    @order = Order.new(obj)
    if params[:order][:address_a] == "0"
      @order.postcode = current_customer.postcode
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_a] == "1"
      @sta = params[:order][:order].to_i
      @order_address = Address.find(@sta)
      @order.postcode = @order_address.postcode
      @order.address  = @order_address.address
      @order.name  = @order_address.name
    elsif params[:order][:address_a] == "2"
      @order.postcode = params[:order][:postcode]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
    end
  end

  def create
    @customer = current_customer
    obj = order_params
    obj[:total_payment] = obj[:total_payment].to_i
    @order = Order.new(obj)
    @order.customer_id = current_customer.id
    @order.save
    create_all_ordered_items(@order)
    redirect_to orders_thanks_path
  end

  def thanks
  end

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  private

  def create_all_ordered_items(order)
    cart_items = current_customer.cart_items
    cart_items.each do |cart_item|
     order_item = OrderItem.new
     order_item.order_id = order.id
     order_item.item_id = cart_item.item_id
     order_item.count = cart_item.count
     order_item.price = cart_item.item.price
     order_item.save
    end
    cart_items.destroy_all
  end

 def order_params
  params.require(:order).permit(:postcode, :address, :name, :shipping_cost, :total_payment, :payment_option, :status)
 end


  def address_params
    params.require(:order).permit(:total_payment, :address_a, :postcode, :name, :address, :order, :payment_option)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="admin-order-show pt-5">
    <h4 class="pb-3">注文履歴詳細</h4>
    <table class="w-100 admin-order-details admin-customer-show">
      <tr class="row pb-2">
        <th class="col-md-2">購入者</th>
        <td class="col-md-10">
          <%= link_to @order.customer.last_name + @order.customer.first_name, admin_customer_path(@order.customer), class: "text-dark" %>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">注文日</th>
        <td class="col-md-10">
          <%= @order.created_at.to_s(:datetime_jp) %>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">配送先</th>
        <td class="col-md-10">
          <div class="admin-order-post mb-2">
            <span>
              〒<%= @order.postcode.to_s.insert(3, "-") %>
            </span>
            <span>
              <%= @order.address %>
            </span>
          </div>
          <div class="admin-order-post">
            <%= @order.name %>
          </div>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">支払方法</th>
        <td class="col-md-10">
          <%= @order.payment_option %>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">注文ステータス</th>
        <td class="col-md-10">
          <%= form_with model: @order, url: admin_order_path(@order), local: true do |f| %>
            <%= f.select :status, ['入金待ち', '入金確認', '製作中', '発送準備中', '発送済み'] %>
            <%= f.submit "更新", class: "btn btn-success ml-4"%>
          <% end %>
        </td>
      </tr>
    </table>

    <div class="admin-order-bottom row mt-5 w-100">
      <table class="table admin-order-items col-md-8">
        <tr>
          <th class="table-active">商品名</th>
          <th class="table-active">単価（税込）</th>
          <th class="text-center table-active">数量</th>
          <th class="text-center table-active">小計</th>
          <th class="table-active">製作ステータス</th>
        </tr>
        <% @order.order_items.each do |order_item| %>
          <tr>
            <td><%= order_item.item.name %></td>
            <td><%= order_item.price.to_s(:delimited) %></td>
            <td class="text-center"><%= order_item.count.to_s(:delimited) %></td>
            <td class="text-center"><%= (order_item.price.to_i * order_item.count.to_i).to_s(:delimited) %></td>
            <td>
              <%= form_with model: order_item, url: admin_order_order_item_path(order_item.id), local: true do |f| %>
                <!--%= f.select :status, {'着手不可':'着手不可', '製作待ち':'製作待ち', '製作中':'製作中', '製作完了':'製作完了'} %>-->
                <!--%= f.select :status, options_for_select(OrderItem.statuses, selected: OrderItem.statuses[order_item.status]) %>-->
                <%= f.select :status, ["着手不可","製作待ち","製作中","製作完了"] %>
                <%= f.submit "更新", class: "btn btn-success ml-3" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <table class="admin-order-details col-md-3 ml-auto mt-auto admin-customer-show">
        <tr>
          <th>商品合計</th>
          <td class="text-right"><%= @order.total_payment.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td class="text-right"><%= @order.shipping_cost.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td class="text-right"><%= (@order.total_payment.to_i + @order.shipping_cost.to_i).to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>