config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }

  resource :customers, only: [:show, :edit, :update]
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw'

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
    }


  root to: 'homes#top'
  get 'home/about' => 'homes#about'


  resources :items, only: [:index, :show]

  post '/orders/confirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:new, :create, :index, :show]



  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]


  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]

    root to: 'homes#top'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end

  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).reverse_order
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end


  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :telephone_number, :is_deleted)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
    def after_sign_up_path_for(resource)
     customers_path(resource)
    end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_inactive_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_inactive_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        redirect_to new_customer_session_path
      end
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # before_action :authenticate_cutomer! アプリケーションコントローラいじる
  # before_action :authenticate_any!
  
  def show
    @customer = current_customer
  end
  
  def edit
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customers_path
    else
      @customer = current_customer
      render :edit
    end
  end
  
  def unsubscribe
    @customer = current_customer
  end
  
  def withdraw
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :telephone_number, :email)
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container">
  <div class="row no-gutters my-5">
    <h4 class="text-dark bg-light p-1 mb-1">会員情報編集</h4>
  </div>
  <div class="row mb-5">
  <div class="offset-sm-1 col-sm-8">
    <%= form_with model: @customer, url: customers_path, method: :patch, local: true do |f| %>
      <div class="form_group row col-sm-12 mb-2">
        <%= f.label :name, "氏名", class: "col-sm-3 col-form-label" %>
        <%= f.text_field :last_name, class: "col-sm-3 mr-3 form-control" %>
        <%= f.text_field :first_name, class: "col-sm-3 form-control" %>
      </div>
      <div class="form_group row col-sm-12 mb-2">
        <%= f.label :name, "フリガナ", class: "col-sm-3 col-form-label" %>
        <%= f.text_field :last_name_kana, class: "col-sm-3 mr-3 form-control" %>
        <%= f.text_field :first_name_kana, class: "col-sm-3 form-control" %>
      </div>
      <div class="form_group row col-sm-12 mb-2">
        <%= f.label :postcode, "郵便番号", class: "col-sm-3 col-form-label" %>
        <%= f.text_field :postcode, class: "col-sm-3 form-control" %>
      </div>
      <div class="form_group row col-sm-12 mb-2">
        <%= f.label :address, "住所", class: "col-sm-3 col-form-label" %>
        <%= f.text_field :address, class: "col-sm-8 form-control" %>
      </div>
      <div class="form_group row col-sm-12 mb-2">
        <%= f.label :telephone_number, "電話番号", class: "col-sm-3 col-form-label" %>
        <%= f.text_field :telephone_number, class: "col-sm-3 form-control" %>
      </div>
      <div class="form_group row col-sm-12 mb-2">
        <%= f.label :email, "メールアドレス", class: "col-sm-3 col-form-label" %>
        <%= f.text_field :email, class: "col-sm-3 form-control" %>
      </div>
      <div class="offset-sm-3 col-sm-8 mt-4">
        <%= f.submit "編集内容を保存", class: "btn btn-sm btn-success mr-5", style: "width: 190px" %>
        <%= link_to '退会する', customers_unsubscribe_path, class: "btn btn-sm btn-danger ml-5", style: "width: 90px" %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/customers/show.html.erb
<div class="container">
  <div class="row no-gutters my-5">
    <h4 class="text-dark bg-light p-1 mb-1">マイページ</h4>
  </div>
  
  <div class="row mb-3">
    <div class="col-sm-8">
      <h5 class="d-inline-block  mr-4 font-weight-bold">登録情報</h5>
      <%= link_to "編集する", edit_customers_path, class: "btn btn-success btn-sm", style: "width: 90px" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
    <table class="table table-bordered border-dark">
      <tr class="table-row">
        <td class="bg-light", style="width: 190px">氏名</td>
        <td><%= @customer.last_name %><%= @customer.first_name %></td>
      </tr>
      <tr class="table-row">
        <td class="bg-light">カナ</td>
        <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
      </tr>
      <tr class="table-row">
        <td class="bg-light">郵便番号</td>
        <td><%= @customer.postcode %></td>
      </tr>
      <tr class="table-row">
        <td class="bg-light">住所</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr class="table-row">
        <td class="bg-light">電話番号</td>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr class="table-row">
        <td class="bg-light">メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
    </table>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-sm-8">
      <h5 class="d-inline-block mr-4 font-weight-bold">配送先</h5>
      <%= link_to "一覧を見る", addresses_path, class: "btn btn-primary btn-sm", style: "width: 120px" %>
    </div>
  </div>

  <div class="row mb-5">
    <div class="col-sm-8">
      <h5 class="d-inline-block mr-4 font-weight-bold">注文履歴</h5>
      <%= link_to "一覧を見る", orders_path, class: "btn btn-primary btn-sm", style: "width: 120px" %>
    </div>
  </div>
</div>

app/views/customers/unsubscribe.html.erb
<div class="container my-5" style="height: 100%">
  <div class="row">
    <div class="col-sm-9 mx-auto">
      <p class="font-weight-bold text-center">本当に退会しますか？</p>
      <div>
        <p class="text-center my-4">退会すると、会員登録情報や<br>これまでの購入履歴が閲覧できなくなります。<br>退会する場合は、「退会する」をクリックしてください。</p>
      </div>
      <div class="text-center">
        <%= link_to '退会しない', edit_customers_path, class: "btn btn-sm btn-primary", style: "width: 120px" %>
        <%= link_to '退会する', customers_withdraw_path, method: :patch, "data-confirm" => "本当に退会しますか？", class: "ml-2 btn btn-sm btn-danger", style: "width: 120px" %>
      </div>
    </div>
  </div>
</div>