config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }

  resource :customers, only: [:show, :edit, :update]
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw'

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
    }


  root to: 'homes#top'
  get 'home/about' => 'homes#about'


  resources :items, only: [:index, :show]

  post '/orders/confirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:new, :create, :index, :show]



  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]


  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]

    root to: 'homes#top'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end

  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item

    validates :customer_id, :item_id, :count, presence: true
    validates :count, numericality: { only_integer: true }

    def subtotal
      item.tax_included_price * count
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items = CartItem.all
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    @cart_items = current_customer.cart_items.all  #同じ商品を異なるタイミングでカートに入れたとき個数が統合される。
      if @cart_item.count != nil
         @cart_items.each do |cart_item|
         if cart_item.item_id == @cart_item.item_id
            new_count= cart_item.count + @cart_item.count
            cart_item.update_attribute(:count, new_count)
            @cart_item.delete
         end
         end
      end
    @cart_item.save
    redirect_to cart_items_path
  end

  def update
    @cart_item = CartItem.find(params[:cart_item][:id])
    @cart_item.update(count: params[:cart_item][:count])
    redirect_to cart_items_path
  end

  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:count,:item_id,:customer_id)
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10"><br>
      <h4 class="mt-3">ショッピングカート</h4>
      <p><%= link_to 'カートを空にする', cart_items_destroy_all_path, class:"btn btn-sm btn-danger", method: :delete %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10">
      <table class="table-light table table-hover">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @sum = 0 %>
          <% @cart_items.each do |cart_item| %>
          <% if cart_item.customer.id == current_customer.id %>
          <tr>
            <td>
              <%= attachment_image_tag cart_item.item, :image, format: 'jpeg', size: "50x50", fallback:"no_image.jpeg" %>
              <%= cart_item.item.name %>
            </td>
            <td>
              ¥<%= cart_item.item.tax_included_price.to_s(:delimited) %>
            </td>
            <td>
              <%=form_with model: cart_item, method: :patch, local:true do |f| %>
                <%=f.select :count, [["1","1"],["2","2"],["3","3"],["4","4"],["5","5"],["6","6"],["7","7"],["8","8"],["9","9"],["10","10"]]%>
                <%=f.hidden_field :id, value: cart_item.id %>
                <%=f.submit'変更',class:"btn btn-sm btn-outline-success"%>
              <% end %>
            </td>
            <td>
              <% @sub_total=cart_item.item.tax_included_price * cart_item.count %>
              ¥<%= @sub_total.to_s(:delimited) %>
            </td>
            <td>
              <%= link_to "削除する", cart_item_path(cart_item), class:"btn btn-sm btn-outline-danger" ,method: :delete %>
            </td>
          </tr>
          <% @sum += @sub_total %>
          <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10">
      <p><%= link_to "買い物を続ける", root_path , class:"btn btn-sm btn-primary" %></p>
    </div>
    <div class="col-md-5">
      <table class="table-light table">
        <thead class="thead-light">
          <tr>
            <th>合計金額</th>
            <td>¥<%= @sum.round.to_s(:delimited) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class ="row">
    <div class="col-md-10">
      <%= link_to "情報入力に進む", new_order_path, class:"btn btn-sm btn-success" %>
    </div>
  </div>
</div>