config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }

  resource :customers, only: [:show, :edit, :update]
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw'

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
    }


  root to: 'homes#top'
  get 'home/about' => 'homes#about'


  resources :items, only: [:index, :show]

  post '/orders/confirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:new, :create, :index, :show]



  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]


  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]

    root to: 'homes#top'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end

  end

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def view_address
      self.postcode.to_s + self.address.to_s + self.name.to_s
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item

    validates :customer_id, :item_id, :count, presence: true
    validates :count, numericality: { only_integer: true }

    def subtotal
      item.tax_included_price * count
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
    
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :order_items, dependent: :destroy
    has_many :cart_items, dependent: :destroy
    attachment :image

    def tax_included_price
      (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  enum status: {
  入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4
  }

  enum payment_option: {クレジットカード: 0, 銀行振込: 1}

  attr_accessor :address_a, :order
  validates :total_payment, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :item

    enum status: {"着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @items = Item.all.order(created_at: :desc).limit(4)  #:desc 新しい順に並べる
  end

  def about
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = Item.all.page(params[:page]).per(8)
  end
  
  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include ApplicationHelper


  before_action :authenticate_customer!

  def new
    @order = Order.new
    @customer = current_customer
    @all = Item.all
    @address = @customer.addresses
    # Address.where(customrer_id: @customer.id)
    @orders = Order.all
  end

  def confirm
    @cart_items = current_customer.cart_items
    @total = 0
    obj = address_params
    obj[:total_payment] = obj[:total_payment].to_i
    @order = Order.new(obj)
    if params[:order][:address_a] == "0"
      @order.postcode = current_customer.postcode
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_a] == "1"
      @sta = params[:order][:order].to_i
      @order_address = Address.find(@sta)
      @order.postcode = @order_address.postcode
      @order.address  = @order_address.address
      @order.name  = @order_address.name
    elsif params[:order][:address_a] == "2"
      @order.postcode = params[:order][:postcode]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
    end
  end

  def create
    @customer = current_customer
    obj = order_params
    obj[:total_payment] = obj[:total_payment].to_i
    @order = Order.new(obj)
    @order.customer_id = current_customer.id
    @order.save
    create_all_ordered_items(@order)
    redirect_to orders_thanks_path
  end

  def thanks
  end

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  private

  def create_all_ordered_items(order)
    cart_items = current_customer.cart_items
    cart_items.each do |cart_item|
     order_item = OrderItem.new
     order_item.order_id = order.id
     order_item.item_id = cart_item.item_id
     order_item.count = cart_item.count
     order_item.price = cart_item.item.price
     order_item.save
    end
    cart_items.destroy_all
  end

 def order_params
  params.require(:order).permit(:postcode, :address, :name, :shipping_cost, :total_payment, :payment_option, :status)
 end


  def address_params
    params.require(:order).permit(:total_payment, :address_a, :postcode, :name, :address, :order, :payment_option)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/"><%= image_tag('logo.jpg') %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <% if admin_signed_in? %>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item nav-link ml-auto"><%= link_to "商品一覧", admin_items_path %></li>
              <li class="nav-item nav-link ml-auto"><%= link_to "会員一覧", admin_customers_path %></li>
              <li class="nav-item nav-link ml-auto"><%= link_to "注文商品一覧", admin_root_path(order_sort: 0)

 %></li>
              <li class="nav-item nav-link ml-auto"><%= link_to "ジャンル一覧", admin_genres_path %></li>
              <li class="nav-item nav-link ml-auto"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
            </ul>
          </div>
          <div class="text-right">
            <br><input type="search" class="st-Header_searchInput" autocomplete="off" placeholder="Serch" value name="q" required>
          </div>
        <% elsif customer_signed_in? %>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <%= "ようこそ #{current_customer.last_name + current_customer.first_name} さん！" %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item nav-link ml-auto"><%= link_to "マイページ", customers_path %></li>
              <li class="nav-item nav-link ml-auto"><%= link_to "商品一覧", items_path %></li>
              <li class="nav-item nav-link ml-auto"><%= link_to "カート", cart_items_path %></li>
              <li class="nav-item nav-link ml-auto"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>
            </ul>
          </div>
        <% else %>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item nav-link ml-auto"><%= link_to "About", home_about_path %></li>
              <li class="nav-item nav-link ml-auto"><%= link_to "商品一覧", items_path %></li>
              <li class="nav-item nav-link ml-auto"><%= link_to "新規登録", new_customer_registration_path %></li>
              <li class="nav-item nav-link ml-auto"><%= link_to "ログイン", new_customer_session_path %></li>
            </ul>
          </div>
        <% end %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>